apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: flask-hello-world-workflow
  namespace: argo
spec:
  entrypoint: build-and-deploy
  arguments:
    parameters:
      - name: hash 
        value: 100
  templates:
    - name: build-and-deploy
      steps:
      - - name: build-docker-image
          template: build-docker-image
      - - name: update-k8s-manifest
          template: update-k8s-manifest

    - name: build-docker-image
      container:
        image: gcr.io/kaniko-project/executor:latest
        command: ["/kaniko/executor"]
        args:
        - --context=git://github.com/MaryiaDevOpsRoom/flask-hello-world.git
        - --dockerfile=./Dockerfile
        - --destination=quay.io/maryia-brauer/flask-hello-world:{{workflow.parameters.hash}}
        volumeMounts:
          - name: kaniko-secret
            mountPath: /kaniko/.docker
      volumes:
        - name: kaniko-secret
          secret:
            secretName: regcred
            items:
              - key: .dockerconfigjson
                path: config.json

    - name: update-k8s-manifest
      container:
        image: bitnami/git
        env:
        - name: EMAIL
          valueFrom:
            secretKeyRef:
              name: github-access
              key: email
        - name: USER
          valueFrom:
            secretKeyRef:
              name: github-access
              key: user
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: github-access
              key: token
        command: ["/bin/sh", "-c"]
        args: 
          - > 
            mkdir gitrepo &&
            git clone --depth=1 https://$USER:$TOKEN@github.com/MaryiaDevOpsRoom/argocd.git gitrepo &&
            cd gitrepo/ &&
            sed -i "s#image: quay.*#image: quay.io/maryia-brauer/flask-hello-world:{{workflow.parameters.hash}}#g" flask-hello-world.yaml &&
            git config user.name $USER &&
            git config user.email $EMAIL &&
            git add . &&
            git commit -m "Upgraded flask-hello-world.yaml thru argo workflows" &&
            git push -u origin main
    
